apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ../manager
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: source-watcher
  spec:
    template:
      spec:
        serviceAccountName: source-controller
images:
- name: fluxcd/source-watcher
  newName: ghcr.io/fluxcd/source-watcher
  newTag: v0.10.0
